name: nippo
description: This is a daily report app, and it's a sample app using Flutter and Firebase.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '^3.5.0'

dependencies:
  adaptive_dialog:
  adaptive_theme:
  cached_network_image:
  cloud_firestore:
  cupertino_icons:
  # 未マージのためgit指定
  # ref. https://github.com/invertase/flutter_desktop_webview_auth/pull/51
  desktop_webview_auth:
    git: https://github.com/andyshephard/flutter_desktop_webview_auth
  firebase_app_check:
  firebase_auth:
  firebase_core:
  flutter:
    sdk: flutter
  flutter_hooks:
  flutter_localizations:
    sdk: flutter
  flutter_svg:
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation:
  gap:
  go_router:
  google_fonts:
  google_sign_in:
  hooks_riverpod:
  intersperse:
  intl:
  json_annotation:
  json_converter_helper:
  package_info_plus:
  provider:
  recase:
  riverpod_annotation:
  shared_preferences:
  simple_logger:
  smooth_highlight:
  tsuruo_kit:
  url_launcher:
  version:

dev_dependencies:
  analyzer:
  build_runner:
  custom_lint:
  flutter_gen:
  flutter_gen_runner:
  freezed:
  go_router_builder:
  icons_launcher:
  json_serializable:
  melos:
  pedantic_mono:
  riverpod_generator:
  riverpod_lint:

dependency_overrides:
  http:

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo/

icons_launcher:
  image_path: 'assets/images/app_icon.png'
  platforms:
    android:
      enable: true
      adaptive_foreground_image: 'assets/images/app_adaptive_foreground.png'
      adaptive_background_image: 'assets/images/app_adaptive_background.png'
      notification_image: 'assets/images/app_adaptive_foreground.png'
      adaptive_monochrome_image: 'assets/images/app_adaptive_monochrome.png'
    ios:
      enable: true
