name: Flutter

on:
  pull_request:
  push:
    branches:
      - '*'
      - '!main'
    # ref. https://qiita.com/nacam403/items/3e2a5df5e88ba20aa76a
    paths:
      - 'lib/**'
      - '!**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Parse an FVM config file into environment variables
        uses: kuhnroyal/flutter-fvm-config-action@v1
        with:
          path: '.fvm/fvm_config.json'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
          # バージョン固定したい場合はこちら
          # flutter-version: ${{ env.FLUTTER_VERSION }}

      # fvmのsdkを参照するために`melos.yaml`に`sdkPath`を指定しているため、
      # より優先度の高い環境変数`MELOS_SDK_PATH`を指定します。
      - name: Set MELOS_SDK_PATH
        run: echo "MELOS_SDK_PATH=${{ env.FLUTTER_ROOT }}" >> $GITHUB_ENV

      - name: Setup Melos
        run: dart pub global activate melos && melos bs

      - name: Analyze
        run: melos run analyze

      - name: Run custom_lint
        run: melos run run:custom_lint

      - name: Check Format
        run: |
          melos run format
          .github/scripts/validate-formatting.sh

      - name: Test
        run: melos run test
